### PR TITLE
Simplecrawler for subpages

### PR DESCRIPTION
**Pull request by DennisBecker**
In this pull request a new option will be added: ```---baseurl```or ```-b```.

When you enable this option, an additional fetch condition will be added which always checks if the parsedUrl from simplecrawler matches the given <url>. This gives the user he opportunity, to create a sitemap.xml for subpages, like all URLs beginning with http://www.example.com/foo

### CODE REVIEW

**Comment by lgraubner** [comment]
Have you tested this? As I can read from the simplecrawler docs `this.crawler.initialPath` does not restrict further requests from accessing `/`.

**Comment by DennisBecker** [comment]
I have tested it before committing. ```this.crawler.initialPath```is the first URL which is called. Just setting this option does not prevent simplecrawler to crawl URLs above this depth. That's why I have added another ```addFetchCondition```callback to prevent this behaviour.

**Comment by DennisBecker** [comment]
I don't understand why the build for node 0.12 has failed while on my repository with the same code it works. See https://travis-ci.org/DennisBecker/node-sitemap-generator-cli/builds/120875515

**Comment by lgraubner** [comment]
I reran it, as far as I can see it was just a timeout, nothing to worry about. Thanks, merged!

**Comment by DennisBecker** [comment]
I will add a log output for pages not matching the base URL.

On huge websites it looks like the crawler won't do anything but in fact it is just removing non-matching URLs

**Pull request merged**
